# Generated by Django 4.2.10 on 2024-03-02 11:14

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user_img",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
