# Generated by Django 4.2.10 on 2024-02-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipe_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_blurb',
            field=models.TextField(default='this_will_be_a_blurb'),
            preserve_default=False,
        ),
    ]
